### ISSUE TITLE
Account balance can't be negative

### ISSUE THREAD

**Issue by markostojanovic087** [Savjee/SavjeeCoin#28]
![image](https://user-images.githubusercontent.com/19815352/63222195-a6475200-c1a4-11e9-8f05-a00d84a4dc0f.png)

Image attached shows the transactions that lead to negative balance on account.
The transaction should not be executed if the user doesn't have enough money.
I suppose the Wallet should be added.

**Comment by Savjee** [comment]
Yep, this shouldn't be possible. It was mainly done for demonstration purposes so you don't have to mine blocks before being able to create transactions.

I'll try to add a simple check soon ;)

**Comment by Savjee** [comment]
This is now fixed by 43341650a6e03d1bab3dc4d148264aeda04af4e5
(Thanks to @hasezoey )
