### ISSUE TITLE
Not enough balance

### ISSUE THREAD

**Issue by FedericoGentile** [Savjee/SavjeeCoin#33]
After downloading the repository and running it I get the following error:

> throw new Error('Not enough balance');

which comes from the following method:
```
 // Making sure that the amount sent is not greater than existing balance
 if (this.getBalanceOfAddress(transaction.fromAddress) < transaction.amount) {
    throw new Error('Not enough balance');
 }
```

The only way I was able to make the code work is by removing such method. Is there any solution to make it function correctly please?

**Comment by Savjee** [comment]
Yes, mine a block first. This will give you a mining reward (50), which you can then spend ;)

Closed for now. But feel free to comment.

**Comment by FedericoGentile** [comment]
Thanks for the reply :)
