### ISSUE TITLE
isChainValid should check that previousHash matches the hash of its previous block?

### ISSUE THREAD

**Issue by ilcasinistareloaded** [Savjee/SavjeeCoin#45]
Hello again, maybe it is not an issue and I'm missing something, but shouldn't method `isChainValid` also check that for each block in the chain its `Block.previousHash` actually match the `Block.hash` of its previous block? Great work, again.

**Comment by Savjee** [comment]
It should, yes!

Can you submit a pull request for this?

**Comment by ilcasinistareloaded** [comment]
Oh, thanks for the offer but I don't know JavaScript; I translated it in a functional language to make it easier to understand (that's the reason of my odd second question in my previous issue: poor understanding of js). So, sorry but I can't help. Thanks for the quick reply!

**Comment by Savjee** [comment]
This has been fixed by @jhonderson
