### ISSUE TITLE
how to connect with local host or database?

### ISSUE THREAD

**Issue by ssupgit** [Savjee/SavjeeCoin#50]
Dear Sir,

Thank you for this inspiring and cool example, but i've found difficulties to connect to database to my local host?
how to do it?
and pardon me..when i do commit git i commit here...how to commit to my own git...sorry in advance...

**Comment by Savjee** [comment]
To store blocks in a database, you'll have to change the blockchain class. Every time it tries to access `this.chain`, you have to connect  to your database and fetch blocks that way.

As for the git issue: you have to change the remote's URL. This will help you:
https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#changing-a-remote-repositorys-url

**Comment by ssupgit** [comment]
Dear Savjee/SavjeeCoin,

Thank you for answering my questions...my skill to code is not so advanced,
but I am so thankful that I can learn from you about this.

But I have difficulties after success with node js that in the youtube
example shown in the front end...

because the frontend is in angular typescript...my ability still not
there...how to make ordinary simple front end maybe to try in my localhost.

I would like to build simple for my ecosystem to educate them about this.


Thank you in advance.

**Comment by Savjee** [comment]
There's not much more I can do for you. I'm not going to implement a database backend for this blockchain. It's only meant for educational purposes, not to be used in production in any way.

Hope you understand that I'm not going to take this on.
Maybe you can find someone else that is willing to help you build this system.

**Comment by ssupgit** [comment]
Yes Sir, Thank you Sir for the education...so much help for me.
keep sharing good things.
