### ISSUE TITLE
Genesis block doesn't follow the difficulty 

### ISSUE THREAD

**Issue by Aminnnnn123** [Savjee/SavjeeCoin#53]
Hey, I just wanted to test the blockchain but then I realized the genesis block's hash doesn't follow the difficulty. I tried solving it by adding this code to the createGenesisBlock() function in line 139 of blockchain.js file:
const genblock = new Block(Date.parse('2017-01-01'), [], '0');
genblock.mineBlock(this.difficulty);
return genblock;

but it didn't work. Can someone please help.

**Comment by csjoshi04** [comment]
Genesis block doesn't have to follow the difficulty, as it is the first block in the chain. Without it, a chain doesn't exist. The difficulty is to ensure that on average every 10  minutes a new block should get mined. Difficulty helps in achieving it.

**Comment by Savjee** [comment]
I agree with @csjoshi04 the genesis block shouldn't follow the current difficulty. 
The Bitcoin codebase does something similar: https://github.com/bitcoin/bitcoin/blob/623745ca74cf3f54b474dac106f5802b7929503f/src/chainparams.cpp#L51
