### ISSUE TITLE
Fix for double spending during mining 

### ISSUE THREAD

**Issue by csjoshi04** [Savjee/SavjeeCoin#54]
`addTransaction()` method checks for double spending by doing `getBalanceOfAddress()` check [link](https://github.com/Savjee/SavjeeCoin/blob/master/src/blockchain.js#L195), but a user can add any number of transactions even if s/he doesnt have the balance. Shouldn't we add the same check for each transaction in the `minePendingTransactions()` [link](https://github.com/Savjee/SavjeeCoin/blob/master/src/blockchain.js#L160), so that we can remove the problem of double spending. If this sounds good, I will raise the pull request.

**Comment by Savjee** [comment]
I'm not sure if I understand this correctly.
As far as I see, it's not possible to call `addTransaction` when you don't have sufficient balance. That is checked here: https://github.com/Savjee/SavjeeCoin/blob/2b9e7882348bfc9ae36910775db49bfb3f2dd35a/src/blockchain.js#L195

To what are you referring when you say "a user can add any number of transactions even if s/he doesnt have the balance" ?

**Comment by guiferpa** [comment]
Hey @Savjee 

First of all, congrats for your initiative, this repository and yours videos series helped me a lot.

About this issue, I have  the same question about double spending and I think that verify only mined transactions in `this.getBalanceOfAddress` it isn't a good solution for this.

Maybe we should verify the [pendingTransactions](https://github.com/Savjee/SavjeeCoin/blob/2b9e7882348bfc9ae36910775db49bfb3f2dd35a/src/blockchain.js#L132) array too, what do you think?

> I'm not sure if I understand this correctly. As far as I see, it's not possible to call `addTransaction` when you don't have sufficient balance. That is checked here:
> 
> https://github.com/Savjee/SavjeeCoin/blob/2b9e7882348bfc9ae36910775db49bfb3f2dd35a/src/blockchain.js#L195
> 
> To what are you referring when you say "a user can add any number of transactions even if s/he doesnt have the balance" ?

**Comment by Savjee** [comment]
I think I start to understand this issue. When a new transaction is added to the pendingTransactions, these checks are performed: 

* "from" and "to" address must be defined
* The transaction must have a valid signature
* The amount must be larger than 0
* You must have a sufficient balance

However, the balance is checked against the balance on chain. Not against what is still pending. So indeed, it's possible to spend more than your balance as there are no checks in "minePendingTransactions".

I see two ways of solving this:
1. Allow people to add these transactions to the list of pending ones and throw them out when mining with `minePendingTransactions`.
1. Add a check to `addTransaction`

I'm inclined to go for option number 1. Normally, blockchains are distributed. Every miner should do it's due diligence and check the pending transactions.

**Comment by Savjee** [comment]
Update!

I implemented a test for this case here: https://github.com/Savjee/SavjeeCoin/blob/95b7fe893d1d2ad667515e092417f55768fc8812/tests/blockchain.test.js#L85

And implemented a fix for `addTransaction`: https://github.com/Savjee/SavjeeCoin/blob/95b7fe893d1d2ad667515e092417f55768fc8812/src/blockchain.js#L201

Could you check these changes?

**Comment by guiferpa** [comment]
That looks like a great solution

> Fixing this in branch: https://github.com/Savjee/SavjeeCoin/tree/issue-54
> 
> I implemented a test for this case here:
> 
> https://github.com/Savjee/SavjeeCoin/blob/95b7fe893d1d2ad667515e092417f55768fc8812/tests/blockchain.test.js#L85
> 
> And implemented a fix for `addTransaction`:
> 
> https://github.com/Savjee/SavjeeCoin/blob/95b7fe893d1d2ad667515e092417f55768fc8812/src/blockchain.js#L201
> 
> Could you check these changes?

**Comment by Savjee** [comment]
Merged in! Thank you both for reporting this (and having the patience for me to understand the issue 😆)
