### ISSUE TITLE
Hard to know the valid src.

### ISSUE THREAD

**Issue by Jeremiah3230** [Savjee/SavjeeCoin#56]
@Savjee 
Thanks a lot for this great work , it surely a great one I have been watching your YouTube video series on this repo, but the SRC structure is a bit different. 
And on the newest update.

**Comment by Savjee** [comment]
Yes, that's correct. A lot of improvements have been made and unfortunately you can't update existing YouTube videos.

You could checkout the earlier commits, like this one:
https://github.com/Savjee/SavjeeCoin/tree/091b6171d3dc9e96c67744459381d695c8d7f3ff

However, some people have contributed fixes that make the chain more secure. So pay attention to that.
