### ISSUE TITLE
TypeError: Transaction is not a constructor

### ISSUE THREAD

**Issue by zacharyburrice** [Savjee/SavjeeCoin#59]
I keep getting the error
TypeError: Transaction is not a constructor
every time I try and run the code. How do I fix this? I know I need to add a constructor, but I am new to this so how do I do that?

**Comment by Savjee** [comment]
Closing this issue, because SavjeeCoin runs fine on my machine and on GitHub Actions.

What version of nodejs are you running? Could it be an outdated one?
Also: did you copy/paste the code or cloned this repository?
