### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getPublic')

### ISSUE THREAD

**Issue by zacharyburrice** [Savjee/SavjeeCoin#60]
I keep getting this error. I have both followed the youtube course and copied the github code, though I keep getting this. Any way I can fix this?

**Comment by Savjee** [comment]
Please provide the full code snippet or clone the entire repository. The code is working fine in GitHub Actions, so I'm assuming that this is an issue on your end.

Closing this issue, but feel free to reply.
