### ISSUE TITLE
Prettier and strict mode

### ISSUE THREAD

**Issue by blackswan-03** [Savjee/SavjeeCoin#64]
I _am_ a bit of a newb, so this may be a dumb question, but should the JS files be re-formatted using VSCode's "Prettier" extension for easier readability, and should they also have "strict" mode implemented to help catch and prevent more errors?

Just wondering🙂

**Comment by Savjee** [comment]
Strict mode is indeed a good idea!
As for Prettier: I will first add it to the build steps, so that it's automatically checked. Then we can correct any errors manually. I don't like some of the formatting changes you've made in the PR's.

**Comment by Savjee** [comment]
Never mind, merged them in!
Thanks ;)
